<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\Power\**" />
    <EmbeddedResource Remove="Tests\Power\**" />
    <None Remove="Tests\Power\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Tests\1.Bitboard - Король\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\1.Bitboard - Король\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\2.Bitboard - Конь\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\3.Bitboard - Ладья\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\4.Bitboard - Слон\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\5.Bitboard - Ферзь\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.10.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.10.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.11.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.11.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.12.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.12.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Fibo\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.10.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.10.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.11.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.11.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.12.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.12.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.13.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.13.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.14.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.14.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
