<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Tests\Power\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Tests\Power\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Power\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.0.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.1.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.10.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.10.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.11.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.11.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.12.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.12.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.13.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.13.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.14.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.14.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.2.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.3.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.4.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.5.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.6.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.7.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.8.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.9.in">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tests\Primes\test.9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
